### ISSUE TITLE
Add a text file with your information to the project

### ISSUE THREAD

**Issue by Kainkun** [AztecGameLab/LongTermGame2#2]
In the folder called "The People", add a text file with your name on it. In the file write your slack username, GitHub username, what your primary role, secondary role if you have one, and what your overall goals are for this project.

**Example**
File Name: KainShepard.txt
Slack Username: Kainkun
GitHub: Kainkun
Primary: Programming
Secondary: Art
My goals are to work together as a team to make a small but complete game that we can all be proud of :)

**Comment by sbarrack** [comment]
Commit to the `Tutorial` branch everyone, please! Only project leads can push to `master` branch.

**Comment by sbarrack** [comment]
Fixed all the unsafe merges etc. Lesson learned, use correct permissions.
